twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        site_name: Darkcraft Project
        site_url: darkcraftproject
        site_url_full: https://darkcraftproject.fr
        site_email: contact@darkctafyproject.fr
        site_address: lorem ipsum lorem ipsum lorem ipsum lorem ipsum
        facebook:
        twitter:
        linkedin:
        youtube:
        instagram:
        github:
        site_author: Adrien Bouthet
        site_version: 0.0.1
        site_soglan: Darkcraft une histoire de tous.
        site_keywords: Blockchain jeux vidéo esport services

when@test:
    twig:
        strict_variables: true
